version: "3.8"
networks:
  default:
    external:
      name: app-network
services:
  database:
    container_name: database
    networks:
      - default
    image: postgres:13.1-alpine
    env_file:
      - database.env
    volumes:
      - ./database-data:/var/lib/postgresql/data/
  app-web:
    container_name: app-web
    networks:
      - default
    image: registry.gitlab.com/omi4571821/app-example:0.1.3-alpha
    command:
      - python
      - manage.py
      - runserver
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - app.env
    depends_on:
      - database